# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket            = "my-terraform-state"
    dynamodb_endpoint = "http://localhost:4566"
    dynamodb_table    = "my-lock-table"
    encrypt           = true
    endpoint          = "http://s3.localhost.localstack.cloud:4566"
    iam_endpoint      = "http://localhost:4566"
    key               = "./terraform.tfstate"
    profile           = "default"
    region            = "us-east-1"
    sts_endpoint      = "http://localhost:4566"
  }
}
